---
baseURL: 'https://andrewich.github.io'
theme: 'ananke'
defaultContentLanguage: 'ru'
languages:
  ru:
    title: 'Мой персональный блог'
    weight: 1
  en:
    title: 'Personal Blog'
    weight: 2
